name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint discord.py[voice] requests datetime asyncio apscheduler psutil discord-py-slash-command python-dotenv
    - name: Analysing the code with pylint
      run: |
        pylint `ls -R|grep .py$|xargs`
